import type { Metadata } from "next";
import { Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import "maplibre-gl/dist/maplibre-gl.css";
import { LayerProvider } from "@/components/LayerProvider";

const inter = Inter({ subsets: ["latin"] });

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  variable: "--font-roboto-condensed",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <LayerProvider>
        <body
          className={`${inter.className} ${robotoCondensed.className} flex h-screen flex-col`}
        >
          <Navbar />
          {children}
        </body>
      </LayerProvider>
    </html>
  );
}
